{
 "title": "Security Dashboard CD",
 "description": "Security Dashboard CD",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_POSTGRESQL", "label": "Data Source", "query": "grafana-postgresql-datasource" },
   {
    "name": "AppName",
    "label": "Application",
    "query": "SELECT DISTINCT app FROM builds"
   },
   {
    "name": "repo_name",
    "label": "Repository",
    "query": "SELECT DISTINCT module FROM builds where app = '${AppName}'"
   },
   {
    "name": "ScanName",
    "label": "Scan Name",
    "query": "SELECT DISTINCT build_number \nFROM builds \nWHERE build_number LIKE 'CD_%'\nAND app = '${AppName}'\nORDER BY build_number DESC \nLIMIT 10;"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "SELECT DISTINCT severity AS severity\nFROM findings;\n"
   },
   { "name": "New", "label": "New", "query": "true,false" },
   { "name": "Suppressed", "label": "Suppressed", "query": "true,false" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; height: 100%; font-size: 32px; font-weight: bold; color: #ffffff; background-color: #1f1f1f; padding: 20px; border-radius: 10px;\">\n    <span style=\"flex-grow: 1; text-align: center;\">Security Dashboard CD</span>\n    <img src=\"https://datafile.accuranet.com/AP.png\" alt=\"Security Logo\" style=\"width: 200px; height: 70px;\">\n</div>\n\n"
   }
  },
  {
   "title": "Summary ( ${ScanName} )",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    severity_levels.severity AS severity,\r\n    COALESCE(findings_data.severity_count, 0) AS severity_count\r\nFROM \r\n    (\r\n        SELECT 'High' AS severity UNION ALL\r\n        SELECT 'Medium' UNION ALL\r\n        SELECT 'Low' UNION ALL\r\n        SELECT 'Info' UNION ALL\r\n        SELECT 'Total'\r\n    ) AS severity_levels\r\nLEFT JOIN \r\n    (\r\n        SELECT \r\n            f.severity AS severity, \r\n            COUNT(*) AS severity_count \r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.app = '${AppName}'\r\n            AND b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND b.module = '${repo_name}' \r\n            AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed})\t\t\t\r\n        GROUP BY \r\n            f.severity\r\n        \r\n        UNION ALL\r\n        \r\n        SELECT \r\n            'Total' AS severity, \r\n            COUNT(*) AS severity_count\r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.app = '${AppName}'\r\n            AND b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND b.module = '${repo_name}' \r\n\t    AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed})\r\n    ) AS findings_data ON severity_levels.severity = findings_data.severity\r\nORDER BY \r\n    CASE \r\n        WHEN severity_levels.severity = 'High' THEN 1 \r\n        WHEN severity_levels.severity = 'Medium' THEN 2 \r\n        WHEN severity_levels.severity = 'Low' THEN 3 \r\n        WHEN severity_levels.severity = 'Info' THEN 4     \r\n        WHEN severity_levels.severity = 'Total' THEN 5 \r\n        ELSE 6 \r\n    END;"
    }
   ]
  },
  {
   "title": "Cloud Security Audit  ( ${ScanName} ) ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    severity_levels.severity AS severity,\r\n    COALESCE(findings_data.severity_count, 0) AS severity_count\r\nFROM \r\n    (\r\n        SELECT 'High' AS severity UNION ALL\r\n        SELECT 'Medium' UNION ALL\r\n        SELECT 'Low' UNION ALL\r\n        SELECT 'Info' UNION ALL\r\n        SELECT 'Total'\r\n    ) AS severity_levels\r\nLEFT JOIN \r\n    (\r\n        SELECT \r\n            f.severity AS severity, \r\n            COUNT(*) AS severity_count \r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND f.toolname IN ('AWS Cloud Security Audit')\r\n            AND b.module = '${repo_name}'\r\n            AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed}) \r\n             \r\n        GROUP BY \r\n            f.severity\r\n        \r\n        UNION ALL\r\n        \r\n        SELECT \r\n            'Total' AS severity, \r\n            COUNT(*) AS severity_count\r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND f.toolname IN ('AWS Cloud Security Audit')\r\n            AND b.module = '${repo_name}' \r\n            AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed})\r\n    ) AS findings_data ON severity_levels.severity = findings_data.severity\r\nORDER BY \r\n    CASE \r\n        WHEN severity_levels.severity = 'High' THEN 1 \r\n        WHEN severity_levels.severity = 'Medium' THEN 2 \r\n        WHEN severity_levels.severity = 'Low' THEN 3 \r\n        WHEN severity_levels.severity = 'Info' THEN 4 \r\n        WHEN severity_levels.severity = 'Total' THEN 5 \r\n        ELSE 6 \r\n    END;\r\n"
    }
   ]
  },
  {
   "title": " DAST Scan ( ${ScanName} ) ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    severity_levels.severity AS severity,\r\n    COALESCE(findings_data.severity_count, 0) AS severity_count\r\nFROM \r\n    (\r\n        SELECT 'High' AS severity UNION ALL\r\n        SELECT 'Medium' UNION ALL\r\n        SELECT 'Low' UNION ALL\r\n        SELECT 'Info' UNION ALL\r\n        SELECT 'Total'\r\n    ) AS severity_levels\r\nLEFT JOIN \r\n    (\r\n        SELECT \r\n            f.severity AS severity, \r\n            COUNT(*) AS severity_count \r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND f.toolname IN ('ZAP Scan')\r\n            AND b.module = '${repo_name}' \r\n            AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed}) \r\n        GROUP BY \r\n            f.severity\r\n        \r\n        UNION ALL\r\n        \r\n        SELECT \r\n            'Total' AS severity, \r\n            COUNT(*) AS severity_count\r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND f.toolname IN ('ZAP Scan')\r\n            AND b.module = '${repo_name}' \r\n            AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed})\r\n    ) AS findings_data ON severity_levels.severity = findings_data.severity\r\nORDER BY \r\n    CASE \r\n        WHEN severity_levels.severity = 'High' THEN 1 \r\n        WHEN severity_levels.severity = 'Medium' THEN 2 \r\n        WHEN severity_levels.severity = 'Low' THEN 3 \r\n        WHEN severity_levels.severity = 'Info' THEN 4 \r\n        WHEN severity_levels.severity = 'Total' THEN 5\r\n        ELSE 6\r\n    END;\r\n"
    }
   ]
  },
  {
   "title": "OS CIS Compliance Scan  ( ${ScanName} ) ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    severity_levels.severity AS severity,\r\n    COALESCE(findings_data.severity_count, 0) AS severity_count\r\nFROM \r\n    (\r\n        SELECT 'High' AS severity UNION ALL\r\n        SELECT 'Medium' UNION ALL\r\n        SELECT 'Low' UNION ALL\r\n        SELECT 'Info' UNION ALL\r\n        SELECT 'Total'\r\n    ) AS severity_levels\r\nLEFT JOIN \r\n    (\r\n        SELECT \r\n            f.severity AS severity, \r\n            COUNT(*) AS severity_count \r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND f.toolname IN ('UBUNTU20-CIS-Audit')\r\n            AND b.module = '${repo_name}' \r\n            AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed}) \r\n        GROUP BY \r\n            f.severity\r\n        \r\n        UNION ALL\r\n        \r\n        SELECT \r\n            'Total' AS severity, \r\n            COUNT(*) AS severity_count\r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND f.toolname IN ('UBUNTU20-CIS-Audit')\r\n            AND b.module = '${repo_name}' \r\n            AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed})\r\n    ) AS findings_data ON severity_levels.severity = findings_data.severity\r\nORDER BY \r\n    CASE \r\n        WHEN severity_levels.severity = 'High' THEN 1 \r\n        WHEN severity_levels.severity = 'Medium' THEN 2 \r\n        WHEN severity_levels.severity = 'Low' THEN 3 \r\n        WHEN severity_levels.severity = 'Info' THEN 4 \r\n        WHEN severity_levels.severity = 'Total' THEN 5\r\n        ELSE 6\r\n    END;\r\n"
    }
   ]
  },
  {
   "title": "Dynamic Kubernetes Security Scan  ( ${ScanName} ) ",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    severity_levels.severity AS severity,\r\n    COALESCE(findings_data.severity_count, 0) AS severity_count\r\nFROM \r\n    (\r\n        SELECT 'High' AS severity UNION ALL\r\n        SELECT 'Medium' UNION ALL\r\n        SELECT 'Low' UNION ALL\r\n        SELECT 'Info' UNION ALL\r\n        SELECT 'Total'\r\n    ) AS severity_levels\r\nLEFT JOIN \r\n    (\r\n        SELECT \r\n            f.severity AS severity, \r\n            COUNT(*) AS severity_count \r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND f.toolname IN ('Kubescape Scanning_CD')\r\n            AND b.module = '${repo_name}' \r\n            AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed}) \r\n        GROUP BY \r\n            f.severity\r\n        \r\n        UNION ALL\r\n        \r\n        SELECT \r\n            'Total' AS severity, \r\n            COUNT(*) AS severity_count\r\n        FROM \r\n            findings f \r\n        JOIN \r\n            builds b ON f.build_id = b.id \r\n        WHERE \r\n            b.build_number = '${ScanName}' \r\n            AND f.severity IN (${severity}) \r\n            AND f.toolname IN ('Kubescape Scanning_CD')\r\n            AND b.module = '${repo_name}' \r\n            AND f.is_new IN (${New}) \r\n            AND f.suppressed IN (${Suppressed})\r\n    ) AS findings_data ON severity_levels.severity = findings_data.severity\r\nORDER BY \r\n    CASE \r\n        WHEN severity_levels.severity = 'High' THEN 1 \r\n        WHEN severity_levels.severity = 'Medium' THEN 2 \r\n        WHEN severity_levels.severity = 'Low' THEN 3 \r\n        WHEN severity_levels.severity = 'Info' THEN 4 \r\n        WHEN severity_levels.severity = 'Total' THEN 5\r\n        ELSE 6 \r\n    END;\r\n"
    }
   ]
  }
 ]
}