{
 "title": "Security Posture",
 "description": "Security Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_POSTGRESQL", "label": "Data Source", "query": "grafana-postgresql-datasource" },
   {
    "name": "AppName",
    "label": "Application",
    "query": "SELECT DISTINCT app FROM builds"
   },
   {
    "name": "repo_name",
    "label": "Repository",
    "query": "SELECT DISTINCT module FROM builds where app = '${AppName}'"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "SELECT DISTINCT severity AS severity\nFROM findings;\n"
   },
   { "name": "New", "label": "New", "query": "true,false" },
   {
    "name": "BuildNames",
    "query": "(\n  SELECT build_number \n  FROM builds \n  WHERE build_number LIKE 'CD_%' \n    AND app = '${AppName}'\n  ORDER BY build_number DESC \n  LIMIT 1\n)\nUNION\n(\n  SELECT build_number \n  FROM builds \n  WHERE build_number LIKE 'CI_%' \n    AND app = '${AppName}'\n  ORDER BY build_number DESC \n  LIMIT 1\n);\n"
   },
   { "name": "Suppressed", "label": "Suppressed", "query": "true,false" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"display: flex; align-items: center; height: 100%; font-size: 32px; font-weight: bold; color: #ffffff; background-color: #1f1f1f; padding: 20px; border-radius: 10px;\">\n    <span style=\"flex-grow: 1; text-align: center;\">Security Posture Dashboard</span>\n    <img src=\"https://datafile.accuranet.com/AP.png\" alt=\"Security Logo\" style=\"width: 200px; height: 70px;\">\n</div>\n\n"
   }
  },
  {
   "title": "Application Security Posture",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    severity_levels.severity,\r\n    COALESCE(severity_data.severity_count, 0) AS severity_count\r\nFROM (\r\n    SELECT 'High' AS severity\r\n    UNION ALL SELECT 'Medium'\r\n    UNION ALL SELECT 'Low'\r\n    UNION ALL SELECT 'Info'\r\n    UNION ALL SELECT 'Total'\r\n) AS severity_levels\r\nLEFT JOIN (\r\n    SELECT \r\n        f.severity,\r\n        COUNT(*) AS severity_count\r\n    FROM \r\n        findings f\r\n    JOIN \r\n        builds b ON f.build_id = b.id\r\n    WHERE \r\n        b.app = '${AppName}'\r\n        AND b.build_number IN (\r\n            SELECT build_number FROM (\r\n                (SELECT build_number \r\n                 FROM builds \r\n                 WHERE app = '${AppName}' AND build_number LIKE 'CI_%'\r\n                 ORDER BY build_number DESC LIMIT 1)\r\n                UNION\r\n                (SELECT build_number \r\n                 FROM builds \r\n                 WHERE app = '${AppName}' AND build_number LIKE 'CD_%'\r\n                 ORDER BY build_number DESC LIMIT 1)\r\n            ) AS latest_builds\r\n        )\r\n        AND f.severity IN (${severity})\r\n        AND f.toolname IN (\r\n            'Dependency Check Scan',\r\n            'SonarQube',\r\n            'Android Security Assessment',\r\n            'iOS Security Assessment',\r\n            'Trufflehog3 Scan',\r\n            'ZAP Scan'\r\n        )\r\n        AND b.module = '${repo_name}'\r\n        AND f.is_new IN (${New})\r\n        AND f.suppressed IN (${Suppressed})\r\n    GROUP BY f.severity\r\n\r\n    UNION ALL\r\n\r\n    SELECT \r\n        'Total' AS severity,\r\n        COUNT(*) AS severity_count\r\n    FROM \r\n        findings f\r\n    JOIN \r\n        builds b ON f.build_id = b.id\r\n    WHERE \r\n        b.app = '${AppName}'\r\n        AND b.build_number IN (\r\n            SELECT build_number FROM (\r\n                (SELECT build_number \r\n                 FROM builds \r\n                 WHERE app = '${AppName}' AND build_number LIKE 'CI_%'\r\n                 ORDER BY build_number DESC LIMIT 1)\r\n                UNION\r\n                (SELECT build_number \r\n                 FROM builds \r\n                 WHERE app = '${AppName}' AND build_number LIKE 'CD_%'\r\n                 ORDER BY build_number DESC LIMIT 1)\r\n            ) AS latest_builds\r\n        )\r\n        AND f.severity IN (${severity})\r\n        AND f.toolname IN (\r\n            'Dependency Check Scan',\r\n            'SonarQube',\r\n            'Android Security Assessment',\r\n            'iOS Security Assessment',\r\n            'Trufflehog3 Scan',\r\n            'ZAP Scan'\r\n        )\r\n        AND b.module = '${repo_name}'\r\n        AND f.is_new IN (${New})\r\n        AND f.suppressed IN (${Suppressed})\r\n) AS severity_data ON severity_levels.severity = severity_data.severity\r\nORDER BY \r\n    CASE \r\n        WHEN severity_levels.severity = 'High' THEN 1\r\n        WHEN severity_levels.severity = 'Medium' THEN 2\r\n        WHEN severity_levels.severity = 'Low' THEN 3\r\n        WHEN severity_levels.severity = 'Info' THEN 4\r\n        WHEN severity_levels.severity = 'Total' THEN 5\r\n        ELSE 6\r\n    END;\r\n"
    }
   ]
  },
  {
   "title": "Infrastructure Security Posture",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    severity_levels.severity AS severity,\r\n    COALESCE(findings_data.severity_count, 0) AS severity_count\r\nFROM\r\n    (\r\n        SELECT 'High' AS severity UNION ALL\r\n        SELECT 'Medium' UNION ALL\r\n        SELECT 'Low' UNION ALL\r\n        SELECT 'Info' UNION ALL\r\n        SELECT 'Total'\r\n    ) AS severity_levels\r\nLEFT JOIN\r\n    (\r\n        SELECT\r\n            f.severity AS severity,\r\n            COUNT(*) AS severity_count\r\n        FROM\r\n            findings f\r\n        JOIN\r\n            builds b ON f.build_id = b.id\r\n        WHERE\r\n            b.app = '${AppName}'\r\n            AND b.build_number IN (\r\n                SELECT build_number FROM (\r\n                    (SELECT build_number FROM builds \r\n                     WHERE app = '${AppName}' AND build_number LIKE 'CI_%' \r\n                     ORDER BY build_number DESC LIMIT 1)\r\n                    UNION\r\n                    (SELECT build_number FROM builds \r\n                     WHERE app = '${AppName}' AND build_number LIKE 'CD_%' \r\n                     ORDER BY build_number DESC LIMIT 1)\r\n                ) AS latest_builds\r\n            )\r\n            AND f.severity IN (${severity})\r\n            AND b.module = '${repo_name}'\r\n            AND f.is_new IN (${New})\r\n            AND f.suppressed IN (${Suppressed})\r\n            AND f.toolname IN (\r\n                'Trivy_MisConfig',\r\n                'Trivy Image Scan',\r\n                'Trivy_CIS',\r\n                'Kubescape Scanning_CI',\r\n                'Kubescape Scanning_CD',\r\n                'AWS Cloud Security Audit',\r\n                'UBUNTU20-CIS-Audit'\r\n            )\r\n        GROUP BY\r\n            f.severity\r\n       \r\n        UNION ALL\r\n       \r\n        SELECT\r\n            'Total' AS severity,\r\n            COUNT(*) AS severity_count\r\n        FROM\r\n            findings f\r\n        JOIN\r\n            builds b ON f.build_id = b.id\r\n        WHERE\r\n            b.app = '${AppName}'\r\n            AND b.build_number IN (\r\n                SELECT build_number FROM (\r\n                    (SELECT build_number FROM builds \r\n                     WHERE app = '${AppName}' AND build_number LIKE 'CI_%' \r\n                     ORDER BY build_number DESC LIMIT 1)\r\n                    UNION\r\n                    (SELECT build_number FROM builds \r\n                     WHERE app = '${AppName}' AND build_number LIKE 'CD_%' \r\n                     ORDER BY build_number DESC LIMIT 1)\r\n                ) AS latest_builds\r\n            )\r\n            AND f.severity IN (${severity})\r\n            AND b.module = '${repo_name}'\r\n            AND f.is_new IN (${New})\r\n            AND f.suppressed IN (${Suppressed})\r\n            AND f.toolname IN (\r\n                'Trivy_MisConfig',\r\n                'Trivy Image Scan',\r\n                'Trivy_CIS',\r\n                'Kubescape Scanning_CI',\r\n                'Kubescape Scanning_CD',\r\n                'AWS Cloud Security Audit',\r\n                'UBUNTU20-CIS-Audit'\r\n            )\r\n    ) AS findings_data ON severity_levels.severity = findings_data.severity\r\nORDER BY\r\n    CASE\r\n        WHEN severity_levels.severity = 'High' THEN 1\r\n        WHEN severity_levels.severity = 'Medium' THEN 2\r\n        WHEN severity_levels.severity = 'Low' THEN 3\r\n        WHEN severity_levels.severity = 'Info' THEN 4\r\n        WHEN severity_levels.severity = 'Total' THEN 5\r\n        ELSE 6\r\n    END;\r\n"
    }
   ]
  },
  {
   "title": "Open High Severity Issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS value\nFROM findings f\nJOIN builds b ON f.build_id = b.id\nWHERE\n  f.severity = 'High'\n  AND b.app = '${AppName}'\n  AND b.build_number IN (\n    SELECT build_number FROM (\n      (SELECT build_number \n       FROM builds \n       WHERE app = '${AppName}' AND build_number LIKE 'CI_%' \n       ORDER BY build_number DESC LIMIT 1)\n      UNION\n      (SELECT build_number \n       FROM builds \n       WHERE app = '${AppName}' AND build_number LIKE 'CD_%' \n       ORDER BY build_number DESC LIMIT 1)\n    ) AS latest_builds\n  );\n"
    }
   ]
  },
  {
   "title": "Open Medium Severity Issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) AS value\nFROM findings f\nJOIN builds b ON f.build_id = b.id\nWHERE\n  f.severity = 'Medium'\n  AND b.app = '${AppName}'\n  AND b.build_number IN (\n    SELECT build_number FROM (\n      (SELECT build_number \n       FROM builds \n       WHERE app = '${AppName}' AND build_number LIKE 'CI_%' \n       ORDER BY build_number DESC LIMIT 1)\n      UNION\n      (SELECT build_number \n       FROM builds \n       WHERE app = '${AppName}' AND build_number LIKE 'CD_%' \n       ORDER BY build_number DESC LIMIT 1)\n    ) AS latest_builds\n  );\n"
    }
   ]
  },
  {
   "title": "Total Suppressed Count",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT \n  f.suppressed,\n  COUNT(*) AS count\nFROM findings f\nJOIN builds b ON f.build_id = b.id\nWHERE \n  b.app = '${AppName}'\n  AND b.build_number IN (\n    SELECT build_number FROM (\n      (SELECT build_number \n       FROM builds \n       WHERE app = '${AppName}' AND build_number LIKE 'CI_%' \n       ORDER BY build_number DESC LIMIT 1)\n      UNION\n      (SELECT build_number \n       FROM builds \n       WHERE app = '${AppName}' AND build_number LIKE 'CD_%' \n       ORDER BY build_number DESC LIMIT 1)\n    ) AS latest_builds\n  )\nGROUP BY f.suppressed;\n"
    }
   ]
  }
 ]
}